### ISSUE TITLE
SoftAttentionDot isn't exactly the attention mechanism from Luong et al., is it?

### ISSUE THREAD

**Issue by MurtyShikhar** [MaximumEntropy/Seq2Seq-PyTorch#10]
In their paper, the input at next time step is the concatenation of h_tilde and the actual input. However, this code seems to use h_tilde as the hidden state for the next time-step LSTM computation.

Brilliant code base, btw.

**Comment by MaximumEntropy** [comment]
Hi, I could be mistaken, but I believe the concatenation of h_tilde and the actual input is what the authors call input feeding and isn't really related to the actual attention mechanism.

**Comment by MurtyShikhar** [comment]
yeah, I just meant it's not exactly the model from their paper, which is fair I guess.
