### ISSUE TITLE
xentropy mask

### ISSUE THREAD

**Issue by rpryzant** [MaximumEntropy/Seq2Seq-PyTorch#11]
Thanks for putting this code up! It's very clean. 

My question is similar to https://github.com/MaximumEntropy/Seq2Seq-PyTorch/issues/6.

At https://github.com/MaximumEntropy/Seq2Seq-PyTorch/blob/master/nmt.py#L184, it seems like you aren't masking your losses, so outputting pad tokens is part of the supervision. Is this the case?

**Comment by MaximumEntropy** [comment]
I mask the loss criterion here - https://github.com/MaximumEntropy/Seq2Seq-PyTorch/blob/master/nmt.py#L92

**Comment by rpryzant** [comment]
Thanks for the pointer!
