### ISSUE TITLE
Questions about the implementation 

### ISSUE THREAD

**Issue by RangoHU** [MaximumEntropy/Seq2Seq-PyTorch#4]
Hello!

I am reading your implementation line by line, and found it's nice and easy to follow. Thanks a lot! But I still have some questions. Since I didn't finish reading yet, I guess I will have more later on.  

You set the requires_grad of two initial hidden states as false ([code](https://github.com/MaximumEntropy/Seq2Seq-PyTorch/blob/master/model.py#L807)). Could you explain why you did this, since I thought they should be true for back-propagation. Also, it is wrong if we set them as true.

**Comment by wjpjet** [comment]
I will be running through this code fully soon, but when I typically see these gradients set as false its because pre-trained models are being loaded (typically with word embeddings). Are the encoders pretrained?

**Comment by cz3344** [comment]
@wjpjet Hi wjpjet. I am also trying to run this code. Have you met the following error running Seq2SeqAttention model?
    41         for i in steps:
     42             hidden = recurrence(input[i], hidden)
---> 43             output.append(isinstance(hidden, tuple) and hidden[0] or hidden)
     44 
     45         output = torch.cat(output, 0).view(input.size(0), *output[0].size())

~/anaconda/envs/pytorch_nmt3.5/lib/python3.5/site-packages/torch/autograd/variable.py in __bool__(self)
    121             return False
    122         raise RuntimeError("bool value of Variable objects containing non-empty " +
--> 123                            torch.typename(self.data) + " is ambiguous")
    124 
    125     __nonzero__ = __bool__

RuntimeError: bool value of Variable objects containing non-empty torch.FloatTensor is ambiguous

**Comment by MaximumEntropy** [comment]
@caozhen-alex I assume you're using PyTorch 0.2. That piece of code on line 43 used to work in 0.1.12 but doesn't any more. Theres a really quick fix which is to replace that line with output.append(hidden[0])

**Comment by MaximumEntropy** [comment]
@RangoHU it is definitely possible to learn the initial hidden state of an RNN (h_0). I just chose not to do it in this implementation. If you look in my refactor branch I no longer have a get_state function. PyTorch now sets the initial hidden and cell states to zero if not specified.

**Comment by cz3344** [comment]
@MaximumEntropy Thx a lot. I fixed that error with your advice!

**Comment by cz3344** [comment]
@MaximumEntropy Hi, I have ran nmt.py. Then how can I use this model to translate my own sentence? Sorry for asking such a noob problem.

**Comment by MaximumEntropy** [comment]
@caozhen-alex good question. I don't have a separate translate.py script yet. But you can probably build one easily by just copying bits of code from `evaluate_model` in `evaluate.py`
