### ISSUE TITLE
Bugs in Seq2Seq model

### ISSUE THREAD

**Issue by JianLiu91** [MaximumEntropy/Seq2Seq-PyTorch#5]
Hi, the code has a nice abstraction and easy to follow. Thanks!!

However, there are some issues in your implement....

([code](https://github.com/MaximumEntropy/Seq2Seq-PyTorch/blob/master/model.py#L510))

If you don't pass `c_t` through a Linear layer from encoder hidden to decoder hidden, then the code crashes. (Encoder and Decoder can have different dimensions)

([code](https://github.com/MaximumEntropy/Seq2Seq-PyTorch/blob/master/model.py#L519))

When `self.decoder.num_layers != 1` the `view` function will crash because of dimension dis-match.

**Comment by MaximumEntropy** [comment]
Hi,

Thanks for pointing this out, I was working on fixing these in the refactor branch. I should merge refactor into master sometime soon and these issues should be fixed.
