### ISSUE TITLE
question about the 'batch_mask'

### ISSUE THREAD

**Issue by ypruan** [MaximumEntropy/Seq2Seq-PyTorch#6]
Hi, your code has a nice abstraction, thanks for your share. But I have a question about the 'attentionLSTM', it seems that you didn' t use any 'ctx_mask' or 'trg_mask' in your code related to attention part, won't this cause error using for attention ? I'm new to pytorch, hope for your reply!

**Comment by bikashg** [comment]
I have the same(similar) question. The mask computed by the get_minibatch() function in data_utils.py is never used at all. Doesn't this hamper training/testing?

**Comment by MaximumEntropy** [comment]
You are absolutely right this means the decoder does indeed attend to the pad tokens in the input however the decoder should be able to learn to put no attention weight on the pad tokens. You can solve this by using using masked_fill with -float('inf') in this line - https://github.com/MaximumEntropy/Seq2Seq-PyTorch/blob/master/model.py#L327.
