### ISSUE TITLE
could you give a sample data, thanks!

### ISSUE THREAD

**Issue by chenwgen** [MaximumEntropy/Seq2Seq-PyTorch#7]
I use data_utils.py to prosess "fr-en.tgz" data,but have many errors. Could you give a sample data, thanks!

**Comment by MaximumEntropy** [comment]
data_utils.py can't read .tgz files. It reads raw text tokenized files. The data format is really simple, src and trg have one tokenized sentence per line such that line `x` in src translates to line `x` in trg.

**Comment by aribenjamin** [comment]
@MaximumEntropy I'd like to make sure that my data processing matches yours. Did you just run:
```
 ~/mosesdecoder/scripts/tokenizer/tokenizer.perl -l en \
    < europarl-v7.fr-en.en    \
    > europarl-v7.fr-en-tok.en
 ~/mosesdecoder/scripts/tokenizer/tokenizer.perl -l fr \
    < europarl-v7.fr-en.fr   \
    > europarl-v7.fr-en-tok.fr
```
Or did you also run the truecasing and cleaning scripts? (http://www.statmt.org/moses/?n=moses.baseline)

**Comment by wishvivek** [comment]
Did you get any answer for this?
