### ISSUE TITLE
how to run the code with beam search?

### ISSUE THREAD

**Issue by wanyao1992** [MaximumEntropy/Seq2Seq-PyTorch#8]
Dear authors,

Thanks for sharing you code. Your code is well structured and easy to read, but I still encounter a problem in running seq2seq with beam search.

In the evaluate.py, you have declared that the beam search is in TODO. And in the decode.py I found that the BeamSearchDecoder has been implemented, so I try to run the decode.py, but it throws a Exception like this:

```
Traceback (most recent call last):
  File "decode.py", line 479, in <module>
    decoder.translate()
  File "decode.py", line 242, in translate
    hypotheses, scores = decoder.decode_batch(j)
  File "decode.py", line 153, in decode_batch
    context
  File "/usr/share/Anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes at most 3 arguments (4 given)
```

So, could you tell me how to run the decode.py or give me some suggestions for implementing the beam search part. It will be highly appreciated for your any suggestions.

Thanks.

**Comment by cz3344** [comment]
@wanyao1992 哥们，你的问题解决了吗？

**Comment by wanyao1992** [comment]
@caozhen-alex Ref: https://github.com/OpenNMT/OpenNMT-py

**Comment by cz3344** [comment]
@wanyao1992 好的，谢谢。 我加你微信了，有空联系。

**Comment by MaximumEntropy** [comment]
Beam search doesn't work right now sorry about that. I'd recommend using OpenNMT-py's beam search as you pointed out.

**Comment by ghost** [comment]
@MaximumEntropy is the beam search working now ?
